import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/Providers";
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "MongoDB y Nextjs",
  description: "Generated by create next with Mongodb",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
         <Navbar />
        <Providers>{children}</Providers></body>
    </html>
  );
}
